a = input()
b = input()
l = max(len(a),len(b))
a = a.rjust(l,"0")
b = b.rjust(l,"0")
a1 = "".join([a[i] for i in range(l) if int(a[i])>=int(b[i])])
b1 = "".join([b[i] for i in range(l) if int(b[i])>=int(a[i])])
print(int(a1) if a1 else "YODA")
print(int(b1) if b1 else "YODA")
