a,b,c = map(int, input().split(" "))

outcomes = []
outcomes.append((a+b)+c)
outcomes.append((a-b)+c)
outcomes.append((a*b)+c)
outcomes.append((a/b)+c)
outcomes.append((a+b)-c)
outcomes.append((a-b)-c)
outcomes.append((a*b)-c)
outcomes.append((a/b)-c)
outcomes.append((a+b)*c)
outcomes.append((a-b)*c)
outcomes.append((a*b)*c)
outcomes.append((a/b)*c)
outcomes.append((a+b)/c)
outcomes.append((a-b)/c)
outcomes.append((a*b)/c)
outcomes.append((a/b)/c)

print(int(min([x for x in outcomes if x >= 0 and x % 1 == 0])))